/* 
 * OSParking, Parking Lot Management Software
 * Copyright (C) 2015 Open Source Parking Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package com.osparking.osparking;

import com.osparking.global.names.JDBCMySQL;
import java.awt.Dimension;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.WARNING_MESSAGE;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import static com.osparking.global.names.DB_Access.parkingLotLocale;
import static com.osparking.global.names.DB_Access.readSettings;
import static com.osparking.global.Globals.*;

/**
 *
 * @author Park, Jongbum <Park, Jongbum at Open Source Parking Inc.>
 */
public class LoginRecordList extends javax.swing.JFrame {
    private static Logger logException = null;
    String searchCondition = "";

    /**
     * Creates new form LoginRecordList
     */
    public LoginRecordList() {
        initComponents();
        
        setIconImages(OSPiconList);
        
        getContentPane().setBackground(PopUpBackground);
        LoginRecordListTopPanel.setBackground(PopUpBackground);
        initUserIDComboBox();
        
        BeginDateChooser.setLocale(parkingLotLocale);
        EndDateChooser.setLocale(parkingLotLocale);
        Date today = new Date();
        BeginDateChooser.setDate(getDateFromGivenDate(today, -7));
        EndDateChooser.setDate(today);
        
        LoginRecordTable.setAutoCreateRowSorter(true);
        RefreshTableContents(BeginDateChooser.getDate(), EndDateChooser.getDate());  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        LoginRecordTable = new javax.swing.JTable();
        LoginRecordListTopPanel = new javax.swing.JPanel();
        UserIDComboBox = new javax.swing.JComboBox();
        SearchLoginRecordButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        BeginDateChooser = new com.toedter.calendar.JDateChooser();
        EndDateChooser = new com.toedter.calendar.JDateChooser();
        CloseFormButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LoginRecordTable.setFont(new java.awt.Font("Dotum", 0, 14)); // NOI18N
        LoginRecordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        LoginRecordTable.setRowHeight(28);
        jScrollPane1.setViewportView(LoginRecordTable);

        UserIDComboBox.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        UserIDComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SearchLoginRecordButton.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        SearchLoginRecordButton.setText("Search");
        SearchLoginRecordButton.setMaximumSize(new java.awt.Dimension(80, 34));
        SearchLoginRecordButton.setMinimumSize(new java.awt.Dimension(80, 34));
        SearchLoginRecordButton.setPreferredSize(new java.awt.Dimension(80, 34));
        SearchLoginRecordButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchLoginRecordButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("~");
        jLabel2.setFocusable(false);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel3.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("User Login Record");
        jLabel3.setFocusable(false);
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        BeginDateChooser.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        BeginDateChooser.setPreferredSize(new java.awt.Dimension(150, 20));

        EndDateChooser.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N

        javax.swing.GroupLayout LoginRecordListTopPanelLayout = new javax.swing.GroupLayout(LoginRecordListTopPanel);
        LoginRecordListTopPanel.setLayout(LoginRecordListTopPanelLayout);
        LoginRecordListTopPanelLayout.setHorizontalGroup(
            LoginRecordListTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginRecordListTopPanelLayout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(UserIDComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BeginDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EndDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SearchLoginRecordButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginRecordListTopPanelLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(94, 94, 94))
        );
        LoginRecordListTopPanelLayout.setVerticalGroup(
            LoginRecordListTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginRecordListTopPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(LoginRecordListTopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UserIDComboBox)
                    .addComponent(SearchLoginRecordButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BeginDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EndDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        CloseFormButton.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        CloseFormButton.setText("Close");
        CloseFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LoginRecordListTopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(14, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CloseFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CloseFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoginRecordListTopPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchLoginRecordButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchLoginRecordButtonActionPerformed
        getDatesRefreshTable();     
    }//GEN-LAST:event_SearchLoginRecordButtonActionPerformed

    private void CloseFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseFormButtonActionPerformed
        setVisible(false);
    }//GEN-LAST:event_CloseFormButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginRecordList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginRecordList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginRecordList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginRecordList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        initializeLoggers();
        checkOptions(args);
        readSettings();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginRecordList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser BeginDateChooser;
    private javax.swing.JButton CloseFormButton;
    private com.toedter.calendar.JDateChooser EndDateChooser;
    private javax.swing.JPanel LoginRecordListTopPanel;
    private javax.swing.JTable LoginRecordTable;
    private javax.swing.JButton SearchLoginRecordButton;
    private javax.swing.JComboBox UserIDComboBox;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void RefreshTableContents(Date beginDate, Date endDate) {
        
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String startDate = dateFormat.format(beginDate);
        String stopDate = dateFormat.format(endDate);

        searchCondition = " where '" + startDate + "' <= date(loginTS) and date(loginTS) <= '" + stopDate + "'";
        
        String user = (String)UserIDComboBox.getSelectedItem();
        if (!user.equals("(everybody)")) {
            searchCondition += " and userID = '" + user + "'";
        }
        
        Connection conn = null;
        PreparedStatement pStmt = null;
        ResultSet rs = null;        
        StringBuffer sb = new StringBuffer();
        
        //<editor-fold desc="--create select statement">
        sb.append("select recNo as 'Order', userID as 'User ID', ");
        
        sb.append(" concat(date_format(loginTS, '%Y-%m-%d '), ");
        sb.append(" if(date_format(loginTS, '%p') ='AM', 'AM', 'PM'),");
        sb.append(" date_format(loginTS, ' %h:%i:%s')) as 'Login Time', ");
        
        sb.append(" concat(date_format(logoutTS, '%Y-%m-%d '), ");
        sb.append(" if(date_format(logoutTS, '%p') ='AM', 'AM', 'PM'),");
        sb.append(" date_format(logoutTS, ' %h:%i:%s')) as 'Logout Time', ");

        sb.append(" concat( ");
        sb.append(  " lpad(timestampdiff(HOUR, loginTS, logoutTS),");
        sb.append(    " if (timestampdiff(HOUR, loginTS, logoutTS) > 9999, 5,");
        sb.append(    " if (timestampdiff(HOUR, loginTS, logoutTS) > 999, 4,");
        sb.append(    " if (timestampdiff(HOUR, loginTS, logoutTS) > 99, 3, 2))), '0'), ':',");
        sb.append(  " lpad(mod(timestampdiff(MINUTE, loginTS, logoutTS), 60), 2, '0'), ':',");
        sb.append(  " lpad(mod(timestampdiff(SECOND, loginTS, logoutTS), 60), 2, '0')) as 'Duration(hh:mm:ss)' ");
        
        sb.append(" from loginrecord" + searchCondition);
        sb.append(" order by recNo desc");
        //</editor-fold>
        
        try {
            conn = JDBCMySQL.getConnection();
            pStmt = conn.prepareStatement(sb.toString());
            rs = pStmt.executeQuery();
            LoginRecordTable.setModel(buildTableModel(rs)); // DbUtils.resultSetToTableModel(rs));
            int dimX = LoginRecordTable.getPreferredSize().width;
            int rowHeight = LoginRecordTable.getRowHeight();
            LoginRecordTable.setPreferredSize(new Dimension(dimX, 
                    rowHeight * LoginRecordTable.getRowCount()));
            SetTableColumnWidth();
        } catch (Exception ex) {
            logParkingException(Level.SEVERE, ex, "(user login record display table: content refreshing)");
        } finally {
            closeDBstuff(conn, pStmt, rs, "accessing login record from DB");            
        }
        
        /**
         * Sets a correct <code>comparator</code> method for the first <code>recNo</code>column
         * Without it, the <code>recNo</code>(an integral type primary key) field of the base table
         * (<code>LoginRecordTable</code>) is sorted as strings where a row with '2' 
         * being greater (appears later in the ascending order sorting) than a row with '10'.
         */        
        TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(LoginRecordTable.getModel());       
        sorter.setComparator(0, com.osparking.global.Globals.comparator);
        LoginRecordTable.setRowSorter(sorter);        
        
    }       

    @SuppressWarnings("unchecked") 
    private void initUserIDComboBox() {
        UserIDComboBox.removeAllItems();
        UserIDComboBox.addItem("(everybody)");
        Connection conn = null;
        Statement stmt = null;
        ResultSet rs = null;
        try {
            conn = JDBCMySQL.getConnection();            
            stmt = conn.createStatement();
            rs = stmt.executeQuery("select id from users_osp order by id");
            while (rs.next()) {
                UserIDComboBox.addItem(rs.getString("id"));
            }
        } catch(Exception ex) {
            logParkingException(Level.SEVERE, ex, "ID combobox data retrieval");
        } finally {
            closeDBstuff(conn, stmt, rs, "ID combobox data retrieval");
        }
    }

    private void SetTableColumnWidth() {
        TableColumnModel tcm = LoginRecordTable.getColumnModel();
        
        ((DefaultTableCellRenderer)LoginRecordTable.getTableHeader().getDefaultRenderer())
                .setHorizontalAlignment(JLabel.CENTER);        
        
        DefaultTableCellRenderer rightRenderer = new DefaultTableCellRenderer();
        rightRenderer.setHorizontalAlignment(JLabel.RIGHT);
        tcm.getColumn(0).setCellRenderer(rightRenderer);  // order : right alignment 
 
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        tcm.getColumn(1).setCellRenderer(centerRenderer);  
        tcm.getColumn(2).setCellRenderer(centerRenderer);  
        tcm.getColumn(3).setCellRenderer(centerRenderer);  
        tcm.getColumn(4).setCellRenderer(centerRenderer);  
        
        // Adjust column width one by one
        SetAColumnWidth(tcm.getColumn(0), 90, 90, 90); // record number column
        SetAColumnWidth(tcm.getColumn(1), 110, 110, 110); // User ID
        SetAColumnWidth(tcm.getColumn(4), 110, 110, 110); // logged in duration
    }

    public void getDatesRefreshTable() {
        Date beginDate = BeginDateChooser.getDate();
        Date endDate = EndDateChooser.getDate();
        
        // Check if both starting and ending dates are entered
        if (beginDate == null || endDate == null) {
            JOptionPane.showConfirmDialog(this, "Please, enter both starting and ending dates!",
                    "Search Range Error", JOptionPane.PLAIN_MESSAGE, WARNING_MESSAGE);             
        } else {
            // Check if dates are chronologically wrong.
            if (beginDate.after(endDate)) {
                JOptionPane.showConfirmDialog(this, "Ending date can't precede starting date!" +
                        System.lineSeparator() +
                        "Please, change search range(dates).", "Wrong Search Range", 
                        JOptionPane.PLAIN_MESSAGE, WARNING_MESSAGE);             
            } else {
                RefreshTableContents(beginDate, endDate);
            }
        }           
    }
}
