/* 
 * OSParking, Parking Lot Management Software
 * Copyright (C) 2015 Open Source Parking Inc.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 3.0 of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301  USA
 */
package com.osparking.osparking;

import com.osparking.vehicle.driver.ManageDrivers;
import static com.osparking.vehicle.driver.ManageDrivers.initAffiliationComboBoxes;
import static com.osparking.vehicle.driver.ManageDrivers.loadComboBoxItems;
import static com.osparking.vehicle.driver.ManageDrivers.loadUnitComboBox;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.MutableComboBoxModel;
import com.osparking.global.names.OSP_enums.BarOperation;
import com.osparking.global.names.ConvComboBoxItem;
import static com.osparking.global.names.DB_Access.readSettings;
import static com.osparking.global.Globals.checkOptions;
import static com.osparking.global.Globals.getTopLeftPointToPutThisFrameAtScreenCenter;
import static com.osparking.global.Globals.OSPiconList;
import static com.osparking.global.Globals.initializeLoggers;
import com.osparking.global.names.InnoComboBoxItem;
import com.osparking.global.names.OSP_enums.DriverCol;
import static com.osparking.global.names.OSP_enums.DriverCol.AffiliationL1;
import static com.osparking.global.names.OSP_enums.DriverCol.AffiliationL2;
import static com.osparking.global.names.OSP_enums.DriverCol.BuildingNo;
import static com.osparking.global.names.OSP_enums.DriverCol.UnitNo;
import com.osparking.global.names.PComboBox;

/**
 *
 * @author Park, Jongbum <Park, Jongbum at Open Source Parking Inc.>
 */
public class VisitingCar extends javax.swing.JFrame {
    ControlGUI parent = null;
    String tagRecognized;
    Date arrivalTime;
    byte gateNo;
    String filename;
    String filenameModified;
    BufferedImage bImg;
    int delay;
    /**
     * Creates new form VisitingCar
     */
    public VisitingCar(ControlGUI parent, String tagRecognized, Date arrivalTime, byte gateNo, 
            String filename, String filenameModified, BufferedImage bImg, int delay) {
        
        initComponents();
        setIconImages(OSPiconList);
        Point screenCenter = getTopLeftPointToPutThisFrameAtScreenCenter(this);
        setLocation(screenCenter);    
        
        this.parent = parent;
        this.tagRecognized = tagRecognized; 
        this.arrivalTime = arrivalTime; 
        this.gateNo = gateNo; 
        this.filename = filename; 
        this.filenameModified = filenameModified; 
        this.bImg = bImg;
        this.delay = delay;

        recogTextField.setText(tagRecognized);
        visitTimeTextField.setText("'" + new SimpleDateFormat ("yy/MM/dd a hh:mm:ss").
                format(arrivalTime));
        
        initAffiliationComboBoxes(highLevelComboBox, lowLevelComboBox, 
                buildingComboBox, unitComboBox);
        visitReasonTextField.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recogTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        visitReasonTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        visitTimeTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        highLevelComboBox = new PComboBox();
        lowLevelComboBox = new PComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buildingComboBox = new PComboBox();
        unitComboBox = new PComboBox();
        openBarButton = new javax.swing.JButton();
        notAllowButton = new javax.swing.JButton();
        closeFormButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visitor Information Entry");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Recognized");

        recogTextField.setEditable(false);
        recogTextField.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        recogTextField.setText("12가3456");

        jLabel4.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Detailed Reason");

        visitReasonTextField.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        visitReasonTextField.setText("Visit coffee shop \"Star Coffee Bean\"");

        jLabel2.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Visit Purpose");

        visitTimeTextField.setEditable(false);
        visitTimeTextField.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        visitTimeTextField.setText("'15.02.05 13:27:04");

        jLabel8.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Visit Time");

        jPanel2.setPreferredSize(new java.awt.Dimension(201, 99));

        jLabel3.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Higher Affiliation");

        jLabel5.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel5.setText("Lower Affiliation");

        highLevelComboBox.setFont(new java.awt.Font("Dotum", 1, 18));
        highLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        highLevelComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                highLevelComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });
        highLevelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                highLevelComboBoxActionPerformed(evt);
            }
        });

        lowLevelComboBox.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        lowLevelComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        lowLevelComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                lowLevelComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lowLevelComboBox, 0, 234, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(highLevelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(highLevelComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lowLevelComboBox))
                .addContainerGap())
        );

        jPanel3.setPreferredSize(new java.awt.Dimension(161, 99));

        jLabel9.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel9.setText("Building");

        jLabel10.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel10.setText("Room/Unit");

        buildingComboBox.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        buildingComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        buildingComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                buildingComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });
        buildingComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingComboBoxActionPerformed(evt);
            }
        });

        unitComboBox.setFont(new java.awt.Font("Dotum", 1, 18)); // NOI18N
        unitComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        unitComboBox.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                unitComboBoxPopupMenuWillBecomeVisible(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(unitComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buildingComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buildingComboBox, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(unitComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(recogTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(visitTimeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(308, 308, 308))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(visitReasonTextField))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recogTextField))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(visitTimeTextField))
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(visitReasonTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        openBarButton.setBackground(new java.awt.Color(102, 255, 102));
        openBarButton.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        openBarButton.setText("Open");
        openBarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openBarButtonActionPerformed(evt);
            }
        });

        notAllowButton.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        notAllowButton.setText("Close Bar");
        notAllowButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notAllowButtonActionPerformed(evt);
            }
        });

        closeFormButton.setFont(new java.awt.Font("Dotum", 1, 14)); // NOI18N
        closeFormButton.setText("Close Form");
        closeFormButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeFormButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(60, 60, 60))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(openBarButton)
                .addGap(18, 18, 18)
                .addComponent(notAllowButton)
                .addGap(18, 18, 18)
                .addComponent(closeFormButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {closeFormButton, notAllowButton, openBarButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(openBarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(notAllowButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeFormButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(68, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openBarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openBarButtonActionPerformed
        welcomeVisitor(true);
    }//GEN-LAST:event_openBarButtonActionPerformed

    private void notAllowButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notAllowButtonActionPerformed
        welcomeVisitor(false);
    }//GEN-LAST:event_notAllowButtonActionPerformed

    private void closeFormButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeFormButtonActionPerformed
        long arrSeqNo = parent.insertDBrecord(gateNo, arrivalTime, tagRecognized, null,
            filenameModified, bImg, -1,  -1, null, BarOperation.REMAIN_CLOSED);    
        parent.isGateBusy[gateNo] = false;
        parent.updateMainForm(gateNo, tagRecognized, arrSeqNo, BarOperation.REMAIN_CLOSED);
        
        dispose();
    }//GEN-LAST:event_closeFormButtonActionPerformed

    @SuppressWarnings("unchecked") 
    private void highLevelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_highLevelComboBoxActionPerformed
        if (highLevelComboBox.isPopupVisible()) {
            MutableComboBoxModel model 
                    = (MutableComboBoxModel)lowLevelComboBox.getModel();
            model.removeElementAt(0);
//            model.insertElementAt(getPrompter(AffiliationL2), 0);
            model.insertElementAt(ManageDrivers.getPrompter(AffiliationL2, highLevelComboBox), 0);
            lowLevelComboBox.setSelectedIndex(0);            
        }        
    }//GEN-LAST:event_highLevelComboBoxActionPerformed

    @SuppressWarnings("unchecked") 
    private void highLevelComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_highLevelComboBoxPopupMenuWillBecomeVisible
        Object selItem = highLevelComboBox.getSelectedItem();

        highLevelComboBox.removeAllItems();
        highLevelComboBox.addItem(ManageDrivers.getPrompter(AffiliationL1, highLevelComboBox));     
        loadComboBoxItems(highLevelComboBox, AffiliationL1, -1);
        highLevelComboBox.setSelectedItem(selItem);         
    }//GEN-LAST:event_highLevelComboBoxPopupMenuWillBecomeVisible

    @SuppressWarnings("unchecked") 
    private void lowLevelComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_lowLevelComboBoxPopupMenuWillBecomeVisible
        Object selItem = lowLevelComboBox.getSelectedItem();
        
        ConvComboBoxItem l1Item = (ConvComboBoxItem)highLevelComboBox.getSelectedItem(); 
        int L1No = (Integer) l1Item.getValue();        // normalize child combobox item 
        lowLevelComboBox.removeAllItems();
        lowLevelComboBox.addItem(ManageDrivers.getPrompter(AffiliationL2, highLevelComboBox));     
        loadComboBoxItems(lowLevelComboBox, DriverCol.AffiliationL2, L1No);        
        lowLevelComboBox.setSelectedItem(selItem);           
    }//GEN-LAST:event_lowLevelComboBoxPopupMenuWillBecomeVisible

    @SuppressWarnings("unchecked") 
    private void buildingComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingComboBoxActionPerformed
        if (buildingComboBox.isPopupVisible()) {
            MutableComboBoxModel model 
                    = (MutableComboBoxModel)unitComboBox.getModel();
            model.removeElementAt(0);
            model.insertElementAt(ManageDrivers.getPrompter(UnitNo, buildingComboBox), 0);
            unitComboBox.setSelectedIndex(0);            
        }
    }//GEN-LAST:event_buildingComboBoxActionPerformed

    @SuppressWarnings("unchecked") 
    private void buildingComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_buildingComboBoxPopupMenuWillBecomeVisible
        Object selItem = buildingComboBox.getSelectedItem();
        
        buildingComboBox.removeAllItems();
        buildingComboBox.addItem(ManageDrivers.getPrompter(BuildingNo, null));     
        loadComboBoxItems(buildingComboBox, BuildingNo, -1);
        buildingComboBox.setSelectedItem(selItem);         
    }//GEN-LAST:event_buildingComboBoxPopupMenuWillBecomeVisible

    private void unitComboBoxPopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_unitComboBoxPopupMenuWillBecomeVisible
        loadUnitComboBox(highLevelComboBox, buildingComboBox, unitComboBox);               
    }//GEN-LAST:event_unitComboBoxPopupMenuWillBecomeVisible

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        long arrSeqNo = parent.insertDBrecord(gateNo, arrivalTime, tagRecognized, null,
            filenameModified, bImg, -1, -1, null, BarOperation.REMAIN_CLOSED);
        parent.isGateBusy[gateNo] = false;        
        parent.updateMainForm(gateNo, tagRecognized, arrSeqNo, BarOperation.REMAIN_CLOSED);
        
        dispose();        
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisitingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisitingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisitingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisitingCar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        initializeLoggers();
        checkOptions(args);
        readSettings();        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisitingCar(null, "12가3456", new Date(), (byte)1, "testImage.jpg", 
                        "2015-05-02_18-59-45_testImage.jpg", null, 8000).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox buildingComboBox;
    private javax.swing.JButton closeFormButton;
    private javax.swing.JComboBox highLevelComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JComboBox lowLevelComboBox;
    private javax.swing.JButton notAllowButton;
    private javax.swing.JButton openBarButton;
    private javax.swing.JTextField recogTextField;
    private javax.swing.JComboBox unitComboBox;
    private javax.swing.JTextField visitReasonTextField;
    private javax.swing.JTextField visitTimeTextField;
    // End of variables declaration//GEN-END:variables

    /**
     * Operate the gate bar if ordered so.
     * Store the visitor arrival record into the database.
     * @param openGate when true, open the gate bar to welcome the visitor.
     *                                  otherwise, let the bar remain closed and disallow the visitor to enter.
     */
    private void welcomeVisitor(boolean openGate) {
        int unitSeqNo;
        int l2No;
        
        if (openGate) {
            parent.raiseGateBar(gateNo, Integer.MAX_VALUE, delay);
        }
        
        if (lowLevelComboBox.getSelectedIndex() == -1) {
            l2No = -1;
        } else {
            l2No = (Integer)
                    ((InnoComboBoxItem)lowLevelComboBox.getSelectedItem()).getKeys()[0];
        }
        if (unitComboBox.getSelectedIndex() == -1) {
            unitSeqNo = -1;
        } else {
            unitSeqNo = (Integer)
                    ((InnoComboBoxItem)unitComboBox.getSelectedItem()).getKeys()[0];
        }
        BarOperation barOperation = BarOperation.MANUAL;
        if (!openGate) {
            barOperation = BarOperation.REMAIN_CLOSED;
        }
        String reason = visitReasonTextField.getText();
        long arrSeqNo = parent.insertDBrecord(gateNo, arrivalTime, tagRecognized, null, filenameModified, 
                bImg, unitSeqNo, l2No, reason.length() == 0 ? null : reason , barOperation);
        parent.updateMainForm(gateNo, tagRecognized, arrSeqNo, barOperation);        
        parent.isGateBusy[gateNo] = false;        
        dispose();
    }
}
